### PR TITLE
Add helm chart

### PR DESCRIPTION
**Pull request by ganievs**
Signed-off-by: Shamil Ganiev <ganiev@pm.me>

### CODE REVIEW

**Comment by Slach** [comment]
@ganievs thanks a lot for contribution. but proposed changes will really hard to maintain in our current pipelines
would you like to change approach to creation helm chart and try to generate instead of copy yaml?

Could you try to apply simple helm generator like https://github.com/arttor/helmify and try to create Helm chart from
exists `clickhouse-operator-install-bundle.yaml` inside `deploy/operator`?

**Comment by guidoiaquinti** [comment]
> Could you try to apply simple helm generator like https://github.com/arttor/helmify and try to create Helm chart from
exists clickhouse-operator-install-bundle.yaml inside deploy/operator?

FYI we used a similar approach [here](https://github.com/PostHog/charts-clickhouse/pull/205)

**Comment by ganievs** [comment]
Hi guys! 
I've done the PR just based on earlier issues and missed up that the manifest generates from code. 
I'm ready to prepare another solution with a generated chart. Do you ready to get it into the main clickhouse-operator repo?

**Comment by ganievs** [comment]
And, maybe it would be better to move our discussion to the related issue?

**Comment by Slach** [comment]
@ganiev we will be happy if you'll provide solution which will maintainable and will generate helm chart automatically from `bundle.yml` and merge it to main repo and also public official Helm chart on https://artifacthub.io/

I could be shell script like `deploy/helm/generate_chart.sh` which use helmify + yq to generate `chart/templates/*` + values.yaml + Chart.yaml

Moreover, helm chart contains same version and appVersion which provide in `release` file in root of repository

And it should only install CRDs + clickhouse-operator  and don't try kind: ClickHouseInstallation, cause this kind shall be managed by separate helm chart

**Comment by ganievs** [comment]
@Slach Thanks for clarification!

**Comment by filimonov** [comment]
See also 

https://artifacthub.io/packages/helm/slamdev/altinity-clickhouse-operator 
https://github.com/TCeason/clickhouse-helm-chart

**Comment by jmeza-xyz** [comment]
Hi team, what is the status of an official helm chart? Is there anything that is needed to get this moving. I am willing to assist where I can.

**Comment by Slach** [comment]
@jmeza-xyz 
chart proposed in this PR is unmantainable
if you provide two charts which will generate automatically from scripts in /deploy/builder/
and will depends on exists parts

we will be happy to merge it

you could look to https://github.com/PostHog/charts-clickhouse/pull/205, and try to adapt it to current repository

**Pull request closed without merging**
