### PR TITLE
Authenticate node communications

### PR DESCRIPTION
**Pull request by chancez**
Please check items PR complies to:
* [x] All commits in the PR are squashed. [More info](https://github.com/Altinity/clickhouse-operator/blob/master/CONTRIBUTING.md#how-to-make-pr) 
* [x] The PR is made into dedicated `next-release` branch, **not into** `master` branch<sup>1</sup>. [More info](https://github.com/Altinity/clickhouse-operator/blob/master/CONTRIBUTING.md#how-to-make-pr)
* [x] The PR is signed. [More info](https://github.com/Altinity/clickhouse-operator/blob/master/CONTRIBUTING.md#sign-your-work)

This is based on #938 , because I wanted to put it up for review, but didn't feel like it was necessary for it to be part of the existing PR. Let me know if you think they should be combined.

### CODE REVIEW

**Comment by alex-zaitsev** [comment]
Hi @chancez , we are making some changes for inter-cluster communication in scope of 0.19 release now. This PR should go after we are done with those changes.

Also, I think it makes sense to move user/password for inter-cluster communication at cluster level. It is not a part of hostTemplate.

**Comment by alex-zaitsev** [comment]
Hi @chancez , we are making some changes for inter-cluster communication in scope of 0.19 release now. This PR should go after we are done with those changes.

Also, I think it makes sense to move user/password for inter-cluster communication at cluster level. It is not a part of hostTemplate.

**Comment by chancez** [comment]
If we move it from the host configuration, how is this supposed to be configured for the auto-generated clusters? https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/ch_config_generator.go#L336-L398

**Comment by alex-zaitsev** [comment]
@sunsingerus , there are two distinct changes here:
1. Using \<secret\> for inter-cluster communication.
2. Using user/pass. 

I think \<secret\> should be default if it passes all tests

**Comment by alex-zaitsev** [comment]
@chancez , we will implement the following:

```
  configuration:
    clusters:
      - name: default
        secure: yes # (default off) turns on HTTPS
        secret:
          auto: yes          # (default) operator creates a secret with name {chi}-{cluster}-interserver-secret and random hash as secret
          value: abcd        # Use explicit secret value
          valueSecretKeyRef: # Use secret reference
            ... 
```

**Comment by chancez** [comment]
@alex-zaitsev Sounds good. I can rebase and I think this PR is pretty close to the configuration you've suggested, so hopefully this can be merged soon then.

**Comment by chancez** [comment]
> @chancez , we will implement the following:
> 
> ```
>   configuration:
>     clusters:
>       - name: default
>         secure: yes # (default off) turns on HTTPS
>         secret:
>           auto: yes          # (default) operator creates a secret with name {chi}-{cluster}-interserver-secret and random hash as secret
>           value: abcd        # Use explicit secret value
>           valueSecretKeyRef: # Use secret reference
>             ... 
> ```

Sounds good, but my question from earlier is still unanswered:
> Thoughts on how to deal with configuring auto generated clusters when internode authentication is configured?

Setting `secure` at the cluster level makes sense to me, but the auto-generated clusters don't have a cluster context. Should I just set `<secure>1</secure>`  if the user defines any clusters with `secure: true`?

**Comment by alex-zaitsev** [comment]
@chancez , secrets for inter-cluster communication are implemented in 0.20.0. See usage examples:
https://github.com/Altinity/clickhouse-operator/blob/0.20.0/docs/chi-examples/21-secure-cluster-secret-01-auto.yaml
https://github.com/Altinity/clickhouse-operator/blob/0.20.0/docs/chi-examples/21-secure-cluster-secret-02-plaintext.yaml
https://github.com/Altinity/clickhouse-operator/blob/0.20.0/docs/chi-examples/21-secure-cluster-secret-03-secret-ref.yaml

**Pull request closed without merging**
