### PR TITLE
metrics:wait all metric data ready

### PR DESCRIPTION
**Pull request by Sallery-X**
If the metrics data consume slowly. we should wait

### CODE REVIEW

**Comment by SalleryWang** [comment]
@alex-zaitsev

**Comment by Sallery-X** [comment]
@sunsingerus please review

**Comment by Sallery-X** [comment]
@sunsingerus

**Comment by sunsingerus** [comment]
Implemented as timeout-ed value in version [0.14.0](https://github.com/Altinity/clickhouse-operator/blob/96dc289ac811fe345b8aa140d259d9121f4e88dd/pkg/apis/metrics/prometheus_writer.go#L164) 
To be released soon

**Pull request closed without merging**
