### PR TITLE
Operator Helm Chart - draft

### PR DESCRIPTION
**Pull request by MatthiasLohr**
This is a first draft of a Helm Chart for deploying the operator on Kubernetes using Helm.

This pull request is opened according to the discussion in #262.

The complete configuration part is missing right now. Discussion in #262 might help to understand about possible configuration parameters and where to put into the files/ConfigMaps for the operator.

### CODE REVIEW

**Comment by faheem-nadeem** [comment]
@MatthiasLohr Any plans to move this forward?

**Comment by MatthiasLohr** [comment]
Theoretically, yes.

The problem: I'm still missing a lot of information, see #262.

**Comment by TCeason** [comment]
@MatthiasLohr

**Comment by MatthiasLohr** [comment]
I'm not experienced with Clickhouse that much, so for me all the configuration directores and files is still a huge black box. So I would need a Clickhouse pro at my side to create a good helm chart.

**Comment by TCeason** [comment]
> I'm not experienced with Clickhouse that much, so for me all the configuration directores and files is still a huge black box. So I would need a Clickhouse pro at my side to create a good helm chart.

Can we learn this operator and charts?

**Comment by MatthiasLohr** [comment]
I don't get what you mean. How is this connected to the clickhouse-operator?

**Comment by TCeason** [comment]
Only as a reference

**Comment by TCeason** [comment]
> I'm not experienced with Clickhouse that much, so for me all the configuration directores and files is still a huge black box. So I would need a Clickhouse pro at my side to create a good helm chart.

Now you question is also about [these](https://github.com/Altinity/clickhouse-operator/issues/262#issue-567068619)?

**Comment by MatthiasLohr** [comment]
This still leaves the question regarding clickhouse/clickhouse-operator knowledge.

**Comment by TCeason** [comment]
> still leaves the question regarding

All right, Could you tell me more about it

**Comment by MatthiasLohr** [comment]
To be honest: I don't remember anymore. I was working on that half a year ago. When I tried to use clickhouse-operator, even using the information provided by @sunsingerus in #262 was not enough to create a stable helm chart which could get everything up and running in a stable manner.

>  I'd propose to make a PR with what you already have into ClickHouse operator repo and continue with unified efforts.

Since "unified efforts" was equal to "nothing happend for a half year" I did not invest more of my own time. Currently, I'm working on other projects, so sadly I'm not going to see enough spare time for working on the chart anymore.

So, I'm sorry for that, but I now decided that I will take down this pull request as well as my fork of the clickhouse-operator repository. This will give other people the chance to create a new pull request creating a helm chart without being marked as duplicate. Maybe, if one of my customers in the future wants to come back to clickhouse, I can invest more time again, but for now I don't see that.

**Pull request closed without merging**
